#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gevent
Version  : 1.0.2
Release  : 3
URL      : https://pypi.python.org/packages/source/g/gevent/gevent-1.0.2.tar.gz
Source0  : https://pypi.python.org/packages/source/g/gevent/gevent-1.0.2.tar.gz
Summary  : Coroutine-based network library
Group    : Development/Tools
License  : BSD-2-Clause
Requires: gevent-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools

%description
libev is a high-performance event loop/event model with lots of features.
(see benchmark at http://libev.schmorp.de/bench.html)

%package python
Summary: python components for the gevent package.
Group: Default

%description python
python components for the gevent package.


%prep
%setup -q -n gevent-1.0.2

%build
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
